  export const CARS = [
    {
      name: "Model S",
      image: "/src/assets/cars/model_S.png",
      batteryChargeTime: "Battery charge time in about 31 min. Battery charged from 10% to 80% at a public DC fast charger.",
      range: "EPA estimated range: 285 mi",
      acceleration: "0-60 mph in 5.4 sec with boost engaged.",
      dailyCharge: "$150/day",
      rating: 4.5,
    },
    {
      name: "Model 3",
      image: "/src/assets/cars/tesla_model3.png",
      batteryChargeTime: "Battery charge time in about 30 min. Battery charged from 10% to 80% at a public DC fast charger.",
      range: "EPA estimated range: 315 mi",
      acceleration: "0-60 mph in 3.1 sec with boost engaged.",
      dailyCharge: "$130/day",
      rating: 4.7,
    },
    {
      name: "CyberTruck",
      image: "/src/assets/cars/cybertruck.png",
      batteryChargeTime: "Battery charge time in about 34 min. Battery charged from 10% to 80% at a public DC fast charger.",
      range: "EPA estimated range: 330 mi",
      acceleration: "0-60 mph in 4.2 sec with boost engaged.",
      dailyCharge: "$200/day",
      rating: 4.6,
    },
    {
      name: "Model X",
      image: "/src/assets/cars/model_X.png",
      batteryChargeTime: "Battery charge time in about 35 min. Battery charged from 10% to 80% at a public DC fast charger.",
      range: "EPA estimated range: 320 mi",
      acceleration: "0-60 mph in 3.5 sec with boost engaged.",
      dailyCharge: "$180/day",
      rating: 4.8,
    },
    {
      name: "NIO ET7",
      image: "/src/assets/cars/nio.png",
      batteryChargeTime: "Battery charge time in about 35 min. Battery charged from 10% to 80% at a public DC fast charger.",
      range: "EPA estimated range: 320 mi",
      acceleration: "0-60 mph in 3.5 sec with boost engaged.",
      dailyCharge: "$160/day",
      rating: 4.4,
    },
    {
      name: "Model Y",
      image: "/src/assets/cars/tesla_modely.png",
      batteryChargeTime: "Battery charge time in about 35 min. Battery charged from 10% to 80% at a public DC fast charger.",
      range: "EPA estimated range: 320 mi",
      acceleration: "0-60 mph in 3.5 sec with boost engaged.",
      dailyCharge: "$140/day",
      rating: 4.3,
    },
  ];